line-length = 140
target-version = "py311"

[lint]
preview = true
select = [
    "E",  # pycodestyle errors
    "F",  # pyflakes
    "I",  # isort
    "W",  # pycodestyle warnings
    "B",  # flake8-bugbear
    "UP", # pyupgrade
    "ANN", # flake8-annotations
    "COM", # flake8-commas: enforce trailing commas in multiline
]
extend-ignore = ["UP009", "ANN401", "COM812"]  # 忽略 UP009 ANN401(Any) COM812(与formatter冲突)

[lint.per-file-ignores]
"__init__.py" = ["F401"]  # Unused imports
"a2c_smcp/utils/async_property/*.py" = ["E", "F", "I", "W", "B", "UP", "ANN"]
"tests/**/*.py" = ["F811", "F401", "B017", "ANN"]  # Redefinition in test files

[lint.isort]
known-first-party = ["a2c_smcp"]

[format]
preview = true
quote-style = "double"
indent-style = "space"
line-ending = "auto"
